# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f8f3c53fffc8a35ed7ff8c3cb39977b4cbb7a899adc8db7842df7b0a6cdd0624d7d01e74e2cadcb3ab4a9a3ee20211c486361b0536209ea79ec611b0ced9dd8

test:
  secret_key_base: b903907eca4df7d2f55c44221406a6d81ca4beeaee28bd43eb605a6a1632163e48a1a1f6af2ab3bede8c129c65c3805cb6ba55aca1da3a35531017eebd5693b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
